config:
  security:
    oauth:
      jwt:
        key: 'algun_codigo_secreto_aeiou'
      client:
        id: frontendapp
        secret: 12345 

spring:
  zipkin:
    base-url: http://zipkin-server:9411/   
    sender:
      type: rabbit
  rabbitmq:
    host: microservicios-rabbitmq38       
  config:
    import: 'optional:configserver:'  