spring:
  application:
    name: items-service
  output:
    ansi:
      console-available: true  

server:
  port: ${PORT:0}

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

configserver:
  name: Registry
  status: Connected to the Registry

resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      items:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      items:
        base-config: defecto